runtime: nodejs18
service: dailybyte-api

env_variables:
  NODE_ENV: production
  PORT: 8080

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  - url: /api/.*
    script: auto
    secure: always

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always

  - url: /(.*\..*)$
    static_files: dist/\1
    upload: dist/(.*\..*)$
    secure: always 